[package]
name = "neowon-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "neowon-app"
path = "src/main.rs"

[dependencies]
neowon-core.workspace = true
neowon-dsp.workspace = true
neowon-sim.workspace = true
neowon-backend.workspace = true
neowon-vds1022.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
bytemuck = "1"
png.workspace = true
tracing.workspace = true

[dev-dependencies]
naga = { version = "29", features = ["wgsl-in"] }
