//! Verification row 14, fallback edition: the committed DAB+-framed
//! HE-AAC v2 fixture (fdk's own encoder) decodes through the adapter.
//!
//! # What this fixture is
//!
//! `dabplus_heaacv2.sf` is a raw DAB+ super frame stream (3 super
//! frames of `subchannel_index` 10, i.e. 1 200 bytes each) built by
//! [`neowon_codec::dabplus::SuperframeEncoder`] from 9 access units
//! encoded by libfdk-aac's own encoder as HE-AAC v2 (AOT 29, 48 kHz
//! stereo, 64 kbit/s CBR, mono core + SBR + PS). The header parameters
//! (48 kHz DAC, SBR, mono core, PS) match the stream exactly. Its
//! `dabplus_heaacv2.asc` is the encoder's own `AudioSpecificConfig`.
//!
//! # What it proves, and the one thing it cannot
//!
//! It proves the adapter + transport chain on a real libfdk-aac
//! HE-AAC v2 bitstream, decoded within the fixture metric against the
//! source PCM, with PS producing stereo from the mono core.
//!
//! It does **not** prove the 960-line transform the DAB+ standard
//! mandates (TS 102 563 clause 5.1): libfdk-aac's encoder accepts
//! `AACENC_GRANULE_LENGTH` values of 1024/512/480/256/240/128/120 only,
//! so no open encoder can produce a 960-line stream. The fixture is
//! therefore 1024-line and the standard-derived DAB+ ASC
//! ([`AudioSpecificConfig::for_dabplus`], `frame_length_960 == true`)
//! would misdescribe it. The default build still asserts the honest
//! boundary: that 960 + SBR config with this AU surfaces
//! [`Error::SbrUnsupportedFrameFamily`]. libfdk-aac's *decoder* does
//! configure the 960 + SBR + PS ASC (asserted in `aac_fixture.rs`);
//! only the fixture's bitstream lacks it.
//!
//! # The metric
//!
//! Best-lag normalised correlation and relative RMS error against the
//! source tone (`dabplus_heaacv2_ref.s16`, generated by ffmpeg lavfi),
//! plus a per-channel Goertzel tone-dominance check — the same metric
//! the other fixture tests use. The measured values are printed by the
//! test (and repeated on failure).

mod common;

use neowon_codec::Error;
#[cfg(feature = "fdk-aac")]
use neowon_codec::aac::SbrSupport;
use neowon_codec::aac::{AacDecoder, AudioSpecificConfig};
use neowon_codec::dabplus::{AccessUnit, SuperframeDecoder, SuperframeHeader};

/// The sub-channel index the fixture was framed for (8 kbit/s units).
const SUBCHANNEL_INDEX: u8 = 10;

fn header() -> SuperframeHeader {
    SuperframeHeader {
        rfa: false,
        dac_rate: true, // 48 kHz DAC
        sbr_flag: true,
        aac_channel_mode: false, // mono core
        ps_flag: true,
        mpeg_surround_config: 0,
    }
}

/// Run the committed super frame stream back through the transport.
///
/// Feeding deliberately awkward chunks exercises the buffering as well
/// as the framing. Returns the AUs as the app would receive them.
fn demux_fixture() -> Vec<AccessUnit> {
    let stream = common::fixture("dabplus_heaacv2.sf");
    let mut decoder = SuperframeDecoder::new(SUBCHANNEL_INDEX).expect("transport decoder");
    let mut superframes = Vec::new();
    for chunk in stream.chunks(97) {
        superframes.extend(decoder.push(chunk));
    }
    assert_eq!(superframes.len(), 3, "three 120 ms super frames");

    let mut aus = Vec::new();
    for (index, superframe) in superframes.iter().enumerate() {
        assert!(superframe.firecode_ok, "super frame {index} Fire code");
        assert_eq!(superframe.header, Some(header()), "super frame {index}");
        assert_eq!(superframe.rs_corrected, 0, "super frame {index}");
        assert_eq!(superframe.rs_uncorrectable, 0, "super frame {index}");
        assert_eq!(superframe.aus.len(), 3, "super frame {index}");
        for au in &superframe.aus {
            assert!(au.crc_ok, "super frame {index} AU CRC");
        }
        aus.extend(superframe.aus.iter().cloned());
    }
    assert_eq!(aus.len(), 9, "9 AUs over 3 super frames");
    aus
}

#[test]
fn dabplus_fixture_round_trips_through_the_transport() {
    // Runs in both builds: framing, RS, Fire code and per-AU CRC all
    // clean, with the last AU of each super frame zero-stuffed inside
    // its CRC-covered region (TS 102 563 clause 5.2).
    let aus = demux_fixture();
    assert_eq!(aus.len(), 9);
    assert!(aus.iter().all(|au| !au.data.is_empty()));
}

#[cfg(not(feature = "fdk-aac"))]
#[test]
fn dabplus_fixture_960_sbr_is_the_surfaced_default_boundary() {
    let aus = demux_fixture();
    assert_eq!(AacDecoder::BACKEND, "oxideav-aac");

    // The config a conformant DAB+ receiver derives from this header.
    let asc = AudioSpecificConfig::for_dabplus(&header());
    assert!(asc.frame_length_960);
    assert_eq!(asc.outer_aot, 29);
    assert_eq!(asc.core_sample_rate(), 24_000);
    assert_eq!(asc.output_sample_rate(), 48_000);

    let mut decoder = AacDecoder::new(asc).expect("decoder");
    let error = decoder
        .decode(&aus[0].data)
        .expect_err("960 + SBR is the default backend's surfaced limitation");
    assert_eq!(error, Error::SbrUnsupportedFrameFamily);
}

#[cfg(feature = "fdk-aac")]
#[test]
fn dabplus_fixture_decodes_with_the_fdk_backend() {
    let aus = demux_fixture();
    assert_eq!(AacDecoder::BACKEND, "fdk-aac");

    // The encoder's own config: same shape as the DAB+ derived one but
    // 1024-line, because no available encoder emits 960 (see the module
    // docs).
    let asc = AudioSpecificConfig::parse(&common::fixture("dabplus_heaacv2.asc"))
        .expect("committed ASC parses");
    let derived = AudioSpecificConfig::for_dabplus(&header());
    assert_eq!(asc.outer_aot, 29, "HE-AAC v2, explicit hierarchical PS");
    assert_eq!(asc.aot, derived.aot);
    assert_eq!(asc.core_sample_rate(), derived.core_sample_rate());
    assert_eq!(asc.channel_configuration, derived.channel_configuration);
    assert_eq!(asc.extension_sample_rate, derived.extension_sample_rate);
    assert!(asc.sbr_present && asc.ps_present);
    assert!(!asc.frame_length_960, "libfdk-aac encodes 1024");
    assert!(derived.frame_length_960, "DAB+ derives 960");
    assert_eq!(
        AudioSpecificConfig::parse(&asc.to_bytes()).expect("round trip"),
        asc
    );

    let mut decoder = AacDecoder::new(asc).expect("fdk configures HE-AAC v2");
    let mut pcm = Vec::new();
    for (index, au) in aus.iter().enumerate() {
        let decoded = decoder
            .decode(&au.data)
            .unwrap_or_else(|error| panic!("AU {index}: {error}"));
        assert_eq!(
            decoded.channels, 2,
            "PS: mono core, stereo out (AU {index})"
        );
        assert_eq!(decoded.sample_rate, 48_000, "AU {index}");
        assert_eq!(decoded.sbr_support, SbrSupport::Ps, "AU {index}");
        pcm.extend_from_slice(&decoded.pcm);
    }

    let reference = common::s16_to_f32(&common::fixture("dabplus_heaacv2_ref.s16"));
    let ours_channels = common::deinterleave(&pcm, 2);
    let reference_channels = common::deinterleave(&reference, 2);
    assert_eq!(ours_channels.len(), 2);
    for (index, (ours, reference)) in ours_channels.iter().zip(&reference_channels).enumerate() {
        let expected = if index == 0 { 440.0 } else { 880.0 };
        let other = if index == 0 { 880.0 } else { 440.0 };
        // Measured on the committed fixture: correlation 0.9999149 (L) /
        // 0.9999198 (R), relative RMS 0.0202 / 0.0130, lag 10 528. The
        // thresholds leave room for libfdk-aac build differences, not for
        // a broken decode.
        let agreement = common::align_and_compare(ours, reference, 12_000);
        common::report_agreement("dabplus_heaacv2.sf", index, &agreement);
        assert!(
            agreement.correlation >= 0.99,
            "channel {index}: correlation {:.4} (lag {}, RMS {:.4})",
            agreement.correlation,
            agreement.lag,
            agreement.relative_rms_error
        );
        assert!(
            agreement.relative_rms_error <= 0.05,
            "channel {index}: relative RMS error {:.4} (correlation {:.4}, lag {})",
            agreement.relative_rms_error,
            agreement.correlation,
            agreement.lag
        );

        let tone = common::goertzel(ours, 48_000.0, expected);
        let leak = common::goertzel(ours, 48_000.0, other);
        assert!(
            tone > 8.0 * leak,
            "channel {index}: {expected} Hz should dominate (tone {tone:.5}, leak {leak:.5})"
        );
        let reference_tone = common::goertzel(reference, 48_000.0, expected);
        let amplitude_ratio = tone / reference_tone;
        assert!(
            (0.3..=2.0).contains(&amplitude_ratio),
            "channel {index}: tone amplitude ratio {amplitude_ratio:.3}"
        );
    }
}

/// Configurations the adapter cannot express are typed errors, not
/// panics — the same contract as the malformed-transport errors above
/// them. Both cases are unreachable through
/// [`AudioSpecificConfig::parse`] or
/// [`AudioSpecificConfig::for_dabplus`]; they only arise from hand-built
/// literals, which the public fields allow.
#[test]
fn inconsistent_configs_are_typed_errors_not_panics() {
    let good = AudioSpecificConfig::for_dabplus(&header());
    let escape = AudioSpecificConfig {
        sampling_frequency_index: 15,
        ..good
    };
    assert!(matches!(AacDecoder::new(escape), Err(Error::InvalidAsc(_))));
    let bad_extension = AudioSpecificConfig {
        extension_sample_rate: Some(96_000),
        ..good
    };
    assert!(matches!(
        AacDecoder::new(bad_extension),
        Err(Error::InvalidAsc(_))
    ));
}

/// A corrupt AU is surfaced, not decoded as silence. (libfdk-aac does
/// conceal genuinely damaged frames and can return OK with silenced
/// output for a config/bitstream mismatch it cannot see; garbage that
/// fails the parser is a typed error. DAB+ AUs are CRC-checked by the
/// transport before they reach a codec.)
#[cfg(feature = "fdk-aac")]
#[test]
fn garbage_access_units_surface_a_typed_error() {
    let asc = AudioSpecificConfig::parse(&common::fixture("dabplus_heaacv2.asc"))
        .expect("committed ASC parses");
    let mut decoder = AacDecoder::new(asc).expect("decoder");
    assert!(matches!(decoder.decode(&[0xAA; 64]), Err(Error::Decode(_))));
    let mut decoder = AacDecoder::new(asc).expect("decoder");
    assert!(matches!(decoder.decode(&[0x00; 64]), Err(Error::Decode(_))));
}
