[package]
name = "neowon-sdr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neowon-core.workspace = true
neowon-dsp.workspace = true
neowon-catalog.workspace = true
neowon-backend.workspace = true
nusb.workspace = true
crossbeam-channel.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
neowon-sim.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true
